---

- name: prepare needed directories
  file:
    path: "/etc/netdata/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - go.d
    - python.d

- name: populate service facts
  service_facts:

- name: create list of services
  set_fact:
    service_list: "{{ service_list|default([]) + [item.name|regex_replace('.service|@')] }}"
  when: item.status | default('disabled') == 'enabled' or item.state == 'running' and item.source == 'sysv'
  loop: "{{ ansible_facts.services.values() | list }}"

- name: remove dublicates from services list
  set_fact:
    service_list: "{{ service_list| unique }}"

- name: check if monit is in list
  set_fact:
    monit_in_list: true
  when: "'monit' in service_list"

- block:
    - name: configure python.d module for nginx
      include_tasks: modules-python.d/nginx.yml
    - name: configure python.d module for weblog
      include_tasks: modules-python.d/web_log.yml
  when: "'nginx' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d module for apache
  include_tasks: modules-python.d/apache.yml
  when: "'apache2' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d module for haproxy
  include_tasks: modules-python.d/haproxy.yml
  when: "'haproxy' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d module for mongo
  include_tasks: modules-python.d/mongo.yml
  when: "'mongodb' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d module for monit
  include_tasks: modules-python.d/monit.yml
  when: force_monit_plugin_installation or monit_in_list|default(false) or netdata_force_all_plugins_installation

- name: configure python.d module for mysql
  include_tasks: modules-python.d/mysql.yml
  when: "'mysql' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d module for php-fpm
  include_tasks: modules-python.d/php-fpm.yml
  when: service_list | join('\n') | regex_search('fpm') or netdata_force_all_plugins_installation

- name: configure python.d module for postgres
  include_tasks: modules-python.d/postgres.yml
  when: "'postgres' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d module for rabbitmq
  include_tasks: modules-python.d/rabbitmq.yml
  when: "'rabbitmq-server' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d module for smartd
  include_tasks: modules-python.d/smartd.yml
  when: "'smartd' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d module for tomcat
  include_tasks: modules-python.d/tomcat.yml
  when: "'tomcat' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d plugin for bind9
  include_tasks: modules-python.d/bind9.yml
  when: "('bind9' in service_list or netdata_force_all_plugins_installation) and netdata_bind9_plugin_version == 'python.d'"

- name: configure python.d plugin for memcached
  include_tasks: modules-python.d/memcached.yml
  when: "'memcached' in service_list or netdata_force_all_plugins_installation"

- name: configure go.d module for prometheus
  include_tasks: modules-go.d/prometheus.yml
  when: ansible_distribution_release != 'focal'

- name: configure go.d module for weblog
  include_tasks: modules-go.d/web_log.yml
  when: netdata_go_d_web_log_plugin_enabled

- name: configure go.d module for bind
  include_tasks: modules-go.d/bind9.yml
  when: "('bind9' in service_list or netdata_force_all_plugins_installation) and netdata_bind9_plugin_version == 'go.d'"

- name: configure go.d module for elasticsearch
  include_tasks: modules-go.d/elasticsearch.yml
  when: "'elasticsearch' in service_list or netdata_force_all_plugins_installation"

- name: configure go.d module for apache
  include_tasks: modules-go.d/apache.yml
  when: "'apache2' in service_list or netdata_force_all_plugins_installation"

- name: configure go.d module for nginx
  include_tasks: modules-go.d/nginx.yml
  when: "'nginx' in service_list or netdata_force_all_plugins_installation"

- name: configure go.d module for php-fpm
  include_tasks: modules-go.d/php-fpm.yml
  when: "service_list | join('\n') | regex_search('fpm') or netdata_force_all_plugins_installation"

- name: configure go.d module for mysql
  include_tasks: modules-go.d/mysql.yml
  when: "'mysql' in service_list or netdata_force_all_plugins_installation"

- name: configure go.d module for redis
  include_tasks: modules-go.d/redis.yml
  when: "'redis' in service_list or netdata_force_all_plugins_installation"
