---
- name: gather required facts
  setup:
    gather_subset: [virtual]
  when: ansible_virtualization_type is not defined

- name: try to get API key from environment
  block:
    - name: look up for NETDATA_API_KEY in env
      set_fact:
        netdata_api_key: "{{ lookup('env', 'NETDATA_API_KEY') }}"

    - name: use API key fron env, if found a suitable one
      set_fact:
        apikey: "{{ netdata_api_key }}"
  when: apikey | length == 0

- name: fail if not received valid API key
  assert:
    that:
      - apikey | regex_search('^[a-zA-Z0-9\\-]+(,[a-zA-Z0-9\\-]+)*$') | string | length >= 36

- name: generate netdata.conf
  template:
    src: netdata-main.j2
    dest: /etc/netdata/netdata.conf
  notify: restart netdata service

- name: generate stream.conf
  template:
    src: netdata-stream.j2
    dest: /etc/netdata/stream.conf
  notify: restart netdata service
