---
- name: Install fping package
  apt: name=fping state=present update_cache=yes cache_valid_time=86400

- name: Deploy fping.conf in /etc/netdata
  template: src=fping.j2 dest=/etc/netdata/fping.conf group=netdata mode=0o640
  notify: restart netdata service
