---
- block:
    - name: gather required facts
      setup:
        gather_subset: [min]
      when: ansible_distribution_release is not defined

    - name: install latest stable version
      include_tasks: setup.yml
      when: netdata_setup == "full" or netdata_setup == "install"

    - name: install fping
      include_tasks: modules-other/fping.yml
      when: netdata_setup == "full" or netdata_setup == "install"

    - name: configuration
      include_tasks: configure.yml
      when: netdata_setup == "full" or netdata_setup == "configure"

    - name: set up python.d and go.d plugins
      include_tasks: configure_plugins.yml
      when: netdata_setup == "full" or netdata_setup == "configure"
  when: not ansible_check_mode
