---
- name: populate service facts
  service_facts:

- name: create list of services
  set_fact:
    service_list: "{{ service_list|default([]) + [item.name|regex_replace('.service|@')] }}"
  when: item.status | default('disabled') == 'enabled' or item.state == 'running' and item.source == 'sysv'
  loop: "{{ ansible_facts.services.values() | list }}"

- name: delete dublicates from services list
  set_fact:
    service_list: "{{ service_list| unique }}"

- name: monit in list
  set_fact:
    monit_in_list: true
  when: "'monit' in service_list"

- name: configuration python.d plugin for nginx
  include_tasks: nginx_and_web_log_plugin_setup.yml
  when: "'nginx' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for apache
  include_tasks: apache_plugin_setup.yml
  when: "'apache2' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for haproxy
  include_tasks: haproxy_plugin_setup.yml
  when: "'haproxy' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for mongo
  include_tasks: mongo_plugin_setup.yml
  when: "'mongodb' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for monit
  include_tasks: monit_plugin_setup.yml
  when: force_monit_plugin_installation or monit_in_list|default(false) or netdata_force_all_plugins_installation

- name: configuration python.d plugin for mysql
  include_tasks: mysql_plugin_setup.yml
  when: "'mysql' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for php-fpm
  include_tasks: phpfpm_plugin_setup.yml
  when: service_list | join('\n') | regex_search('fpm') or netdata_force_all_plugins_installation

- name: configuration python.d plugin for postgres
  include_tasks: postgres_plugin_setup.yml
  when: "'postgres' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for rabbitmq
  include_tasks: rabbitmq_plugin_setup.yml
  when: "'rabbitmq-server' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for smartd
  include_tasks: smartd_plugin_setup.yml
  when: "'smartd' in service_list or netdata_force_all_plugins_installation"

- name: configuration python.d plugin for tomcat
  include_tasks: tomcat_plugin_setup.yml
  when: "'tomcat' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d plugin for bind9
  include_tasks: "{{ item }}"
  loop:
    - bind9_plugin_setup.yml
    - go_d_bind9_plugin_setup.yml
  when: "'bind9' in service_list or netdata_force_all_plugins_installation"

- name: configure python.d plugin for memcached
  include_tasks: memcached_plugin_setup.yml
  when: "'memcached' in service_list or netdata_force_all_plugins_installation"

- name: configuration go.d plugin for prometheus
  include_tasks: prometheus_plugin_setup.yml
  when: ansible_distribution_release != 'focal'

- name: configuration go.d plugin for weblog
  include_tasks: go_d_weblog_plugin_setup.yml
  when: netdata_go_d_web_log_plugin_enabled
