---
- name: create netdata go.d.plugin configuration for prometheus
  block:
    - name: ensure that netdata/go.d directory exists
      file:
        path: /etc/netdata/go.d
        state: directory
        mode: 0755
    - name: generate go.d/prometheus.conf
      template:
        src: prometheus.j2
        dest: /etc/netdata/go.d/prometheus.conf
        mode: 0644
