---

- name: enable rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  when: not netdata_force_all_plugins_installation

- name: add RabbitMQ user for metric collection
  rabbitmq_user:
    user: netdata
    password: "{{ lookup('password', '/tmp/rabbitpass length=16 chars=ascii_letters,digits') }}"
    configure_priv: .*
    read_priv: .*
    write_priv: ''
    tags: monitoring
  register: created_rabbitmq_user
  when: not netdata_force_all_plugins_installation and (ansible_virtualization_type != 'lxc' or netdata_force_create_db_user)

- name: generate python.d/rabbitmq.conf  # noqa 503
  template:
    src: modules-python.d/rabbitmq.j2
    dest: /etc/netdata/python.d/rabbitmq.conf
    group: netdata
    mode: 0o640
  notify: restart netdata service
  when: created_rabbitmq_user.changed|default('false')
