---

- name: generate python.d/web_log.conf
  template:
    src: modules-python.d/web_log.j2
    dest: /etc/netdata/python.d/web_log.conf
    group: netdata
    mode: 0640
  notify: restart netdata service
  when: netdata_python_web_lob_plugin_enabled
