---

- name: generate go.d/elasticsearch.conf
  template:
    src: modules-go.d/elasticsearch.j2
    dest: /etc/netdata/go.d/elasticsearch.conf
    group: netdata
    mode: 0640
  notify: restart netdata service
